ls:
  .dir: snake_case # | exists:1
  .json: exists:1-2
  .bzl: snake_case
  .sh: snake_case
  .bazel: SCREAMING_SNAKE_CASE
  .go: snake_case
  .yaml: snake_case
  .js: snake_case

  deployments:
    .dir: exists:1
    .json: exists:1

  peter:
    .dir: exists:1
    .*: PascalCase | exists:2
    .js: exists:3 | snake_case
    .vue: exists:1

    '*':
      .dir: exists:1
      .vue: snake_case

ignore:
  - .git
  - .github
  - .idea
  - genhtml
  - bazel-*
  - deployments/npm/pnpm-lock.yaml