ls:
  .dir: snake_case
  .json: snake_case
  .bzl: snake_case
  .sh: snake_case
  .bazel: SCREAMING_SNAKE_CASE
  .go: snake_case
  .yaml: snake_case
  .js: snake_case

ignore:
  - .git
  - .github
  - .idea
  - genhtml
  - bazel-*
  - gha-*
  - deployments/npm/pnpm-lock.yaml