name: CI
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/bazel-public/bazel@sha256:7318b89458263c20e9b98ac7864769ba68bb86ff2dd33980b42ee33a1591df17 # v6.2.0
      env:
        GITHUB_WORKSPACE: /home/ubuntu
    steps:
      - run: mkdir -p ${GITHUB_WORKSPACE} && mkdir -p ${GITHUB_PATH}
      - uses: actions/checkout@v3
        with:
          path: app
      - run: set -eu && ls -al
      - run: bazel --output_user_root=/home/ubuntu test //...
      - run: bazel --output_user_root=/home/ubuntu build //...
