name: CI
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/bazel-public/bazel@sha256:7318b89458263c20e9b98ac7864769ba68bb86ff2dd33980b42ee33a1591df17 # v6.2.0
      options: --user root
    steps:
      - run: set -eu
      - uses: actions/checkout@v3
      - run: bazel test //...
      - run: bazel build //...